### ISSUE TITLE
Broken with the new Discord update

### ISSUE THREAD

**Issue by iblowmymind** [Bricklou/powercord-pindms#11]
Discord renamed most of the CSS classes in the client, so the plugin doesn't function as intended anymore.
The broken parts of the theme (as far as I've noticed):

- [ ] DM lists won't expand / collapse
- [ ] Mismatching fonts in the list titles

**Comment by Bricklou** [comment]
I know, sadly I don't have the time to fix it.
Feel free to contribute if you want.

**Comment by E-boi** [comment]
should be fixed now. update the plugin
