### ISSUE TITLE
Collapse all other dms

### ISSUE THREAD

**Issue by lelboatz** [Bricklou/powercord-pindms#12]
Is there an option to collapse all other dms?

**Comment by Bricklou** [comment]
Can you be more explicit about your feature request?

**Comment by lelboatz** [comment]
> Can you be more explicit about your feature request?

The feature I'm asking about is the ability to collapse all other DMs that aren't categorized just like how I am able to collapse categorized DMs.

**Comment by Bricklou** [comment]
Oh, ok
How would you see it ? A button in settings or something else?

**Comment by lelboatz** [comment]
> 

![image](https://user-images.githubusercontent.com/69434290/148879696-b173ff4d-6661-4d3c-a6b2-c5a21c386b6d.png)
There would be a button right next to the +

**Comment by Bricklou** [comment]
This should work now, if you find any issue, don't hesitate to signal it in this issue.
