### ISSUE TITLE
Unpinning a user from a category doesn't work

### ISSUE THREAD

**Issue by iblowmymind** [Bricklou/powercord-pindms#13]
Sorry for bothering with another issue! I currently cannot unpin users from a category (no unpin icon shows) once I add them in one.

**Comment by Bricklou** [comment]
since discord did a lot of broken change, there are no way anymore to add or remove from context menu
the only way for now is to remove it from the config file

**Comment by iblowmymind** [comment]
oh- that's a shame, can you maybe make a GUI in settings to ease the editing of categories, then? i don't think that should be impossible even with the new update

**Comment by thakyZ** [comment]
Here are the errors received in the developer console related to this bug.
```js
Uncaught (in promise) TypeError: Cannot read property 'default' of null
    at _injectPeopleList (\powercord\src\Powercord\plugins\powercord-pindms\modules\FriendsList.js:212:32)
VM1477 \powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuGroup.js:131 Uncaught (in promise)
```   
```js
TypeError: Cannot read property 'default' of null
    at PinDMs.module.exports \powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuGroup.js:131:7)
VM1478 \powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuUser.js:134 Uncaught (in promise)
```   
```js
TypeError: Cannot read property 'default' of null
    at PinDMs.module.exports (\powercord\src\Powercord\plugins\powercord-pindms\modules\ContextMenuUser.js:134:7)
```

**Comment by iblowmymind** [comment]
Oh, and on another sidenote, regular DMs get higher up in a group list based on most recent messages but this behaviour is not present on group chats. Is there any technical reason behind this?

**Comment by Bricklou** [comment]
It shouldn't have problems but that's all I can say. There is maybe some unexpected behaviours

**Comment by iblowmymind** [comment]
But this happened before the new discord classes update. As far as I can remember, I think

**Comment by Bricklou** [comment]
Probably, this is not related to the breaking changes

**Comment by iblowmymind** [comment]
True, but I'm just mentioning it just in case. Is it fixable?

**Comment by Bricklou** [comment]
I'll try to look at it when I have time.

**Comment by iblowmymind** [comment]
Alright, thanks!

**Comment by iblowmymind** [comment]
This is fixed with the latest update, although I'll keep the issue open because of the groupchats not sorting over recent message issue.

**Comment by Bricklou** [comment]
f562bd1 should fix the group sorting issue, can you test it and confirm that the issues has been fixed ?

**Comment by iblowmymind** [comment]
It's fixed, thanks! Closing the issue.
