### ISSUE TITLE
Remove extra features such as the friendslist additions

### ISSUE THREAD

**Issue by Alfred-207** [Bricklou/powercord-pindms#4]
The plugin overall just seems like the port of PinDMs, but upon installation its all of this jumble that I didn't want. Yes, you can disable it, but I feel that its unnecessary to add all of this in, and if its not already on Powercord, you should simply just make separate plugins.

**Comment by Bricklou** [comment]
To explain why there are more features than excepted. At the beginning, I wanted to only have plugin porting the original PinDMs and after talking with @E-boi, we decide to merge Better Friend List inside this plugin.

The goal is to enhance user experience about the friend system, but you're right about the thing that the plugin name doesn't match with provided features. I might see about renaming it.
