### ISSUE TITLE
collapse on pins not working

### ISSUE THREAD

**Issue by sfarmani** [Bricklou/powercord-pindms#5]
I can't seem to collapse or uncollapse the pins
they only work if i click on them, change to a guild, go back to dms
and sometimes it works, but only a couple of times.

It was working fully before, but now it doesn't

![image](https://user-images.githubusercontent.com/15093212/140200608-44ec0565-cd5d-4daa-831c-80e827d9eddd.png)
the red is supposed to be open, but its not, and the numbers definitely shows there's at least 1 person pinned

**Comment by Bricklou** [comment]
Oh no... Look like the render update bug is still here...

**Comment by sfarmani** [comment]
Oh, idk if I should add-on to this or make a new one, but it seems that any notifications from a pinned DM does not make a sound...
I only noticed this recently.
